import turtle
t=turtle
t.color("blue")
t.bgcolor("black")
t.penup()
t.backward(460)
t.right(90)
t.forward(380)
t.pendown()
def square(sidelength):
    for i in range(4):
        t.left(90)
        t.forward(200)
square(2)
t.right(180)
t.forward(200)
t.right(45)
t.forward(150)
t.right(94)
t.forward(145)
t.right(41)
t.forward(200)
t.penup()
t.right(90)
t.forward(215)
t.left(180)
t.pendown()
import turtle
tu=turtle
tu.color("green")
tu.pensize(20)
tu.forward(900)
tu.penup()
tu.backward(800)
import turtle
tur=turtle
tur.color("saddle brown")
tur.left(180)
tur.backward(50)
tur.backward(180)
tur.right(90)
tur.pensize(20)
tur.pendown()
tur.forward(190)
tur.color("green")
tur.penup()
tur.right(90)
tur.forward(10)
tur.pendown()
tur.begin_fill()
tur.circle(50)
tur.end_fill()
import turtle
turr=turtle
turr.penup()
turr.left(90)
turr.forward(450)
turr.left(90)
tur.forward(200)
turr.pendown()
turr.begin_fill()
turr.color("yellow")
tur.circle(60)
turr.end_fill()
tu.exitonclick()